export const RESERVED_SUBDOMAINS: ReadonlySet<string> = Object.freeze(
  new Set([
    'admin',
    'www',
    'api',
    'verbilo',
    'app',
    'mail',
    'ftp',
    'dev',
    'staging',
    'prod',
    'production',
    'static',
    'cdn',
    'assets',
    'docs',
    'support',
    'help',
    'auth',
    'login',
    'signup',
    'public',
    'internal',
  ]),
);
